name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted   # use our EC2 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop existing container (if any)
        run: |
          docker stop myapp || true
          docker rm myapp || true

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Run Docker container
        run: |
          docker run -d -p 80:80 --name myapp myapp:latest
